name: 🗃️ Data Modeling
description: Help gbnc with its data extraction and processing.
labels: ["data modeling"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have searched [open and closed data issues](https://github.com/rti/gbnc/issues?q=is%3Aopen+is%3Aissue+label%3A%22data+modeling%22)
          required: true
        - label: I agree to follow [Wikimedia's Code of Conduct](https://www.mediawiki.org/wiki/Code_of_Conduct)
          required: true
  - type: input
    id: languagec
    attributes:
      label: Languages
      placeholder: Tell us which languages this relates to.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Let us know what your idea is!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for supporting our data modeling efforts!
